name: Singularity Build (docker)
on: 
  push:

    # Edit the branches here if you want to change deploy behavior
    branches:
      - main

  # Do the builds on all pull requests (to test them)
  pull_request: []

jobs:
  changes:
    name: "Changed Singularity Recipes"
    runs-on: ubuntu-latest

    outputs:
      changed_files: ${{ steps.combine.outputs.changed_files }}

    steps:
      - id: files
        uses: Ana06/get-changed-files@v2.0.0
        with:
          format: 'json'

      - id: combine
        run: |
          echo '${{ steps.files.outputs.added_modified }}' > added_modified.json
          echo '${{ steps.files.outputs.renamed }}' > renamed.json
          changes="$(cat added_modified.json renamed.json | jq -r -s 'add | unique | sort')"
          echo "$changes"
          echo ::set-output name=changed_files::$(echo $changes | jq -c .)

  build-test-containers:
    needs:
      - changes
    runs-on: ubuntu-latest
    strategy:
      # Keep going on other deployments if anything bloops
      fail-fast: false
      matrix:
        singularity_version:
          - '3.8.3'
        program:
          - 'lsdalton'
          #- 'dalton'
        version:
          - 'v2020.0'
          - 'master'
        variant:
          - 'omp'
          - 'mpi+omp'
          - 'mpi'
        exclude:
          ## excludes Dalton and omp
          #- program: 'dalton'
          #  variant: 'omp'
          ## excludes Dalton and mpi+omp
          #- program: 'dalton'
          #  variant: 'mpi+omp'
          # excludes LSDalton and mpi
          - program: 'lsdalton'
            variant: 'mpi'

    container:
      image: quay.io/singularity/singularity:v${{ matrix.singularity_version }}
      options: --privileged

    name: Build ${{ matrix.program }}-${{ matrix.version }}-${{ matrix.variant }}
    steps:

      - name: Check out code for the container builds
        uses: actions/checkout@v2

      - name: Continue if Singularity Recipe
        run: |
          apk add jq
          # Continue if the Singularity recipes changed
          echo '${{ needs.changes.outputs.changed_files }}' > changed_files.json
          changed="$(cat changed_files.json | jq '.[] | test("Singularity.${{ matrix.program }}-${{ matrix.variant }}")')"
          if [[ "$changed" == "true" ]]; then
             echo "keepgoing=true" >> $GITHUB_ENV
          fi

      - name: Build Container
        if: ${{ env.keepgoing == 'true' }}
        env:
          image_name: ${{ matrix.program }}-${{ matrix.version }}-${{ matrix.variant }}
          recipe: Singularity.${{ matrix.program }}-${{ matrix.variant }}
        run: |
          ls
          if [[ "${keepgoing}" == "true" ]]; then
             sed "s/@_VERSION_@/${{ matrix.version }}/g" "$recipe" > Singularity."$image_name"
             sudo -E singularity build container.sif Singularity."$image_name"
             echo "Image name is $image_name."
             echo "IMAGE_NAME=$image_name" >> $GITHUB_ENV
             # use latest as tag
             tag="latest"
             # Build the container and name by tag
             echo "Tag is $tag."
             echo "TAG=$tag" >> $GITHUB_ENV
          else
             echo "No changes in ${{ matrix.program }}-${{ matrix.version }}-${{ matrix.variant }}."
             echo "Present working directory: $PWD"
             ls
          fi

      - name: Login and Deploy Container
        if: (github.event_name != 'pull_request')
        env:
          keepgoing: ${{ env.keepgoing }}
        run: |         
          if [[ "${keepgoing}" == "true" ]]; then
             echo ${{ secrets.GITHUB_TOKEN }} | singularity remote login -u ${{ secrets.GHCR_USERNAME }} --password-stdin oras://ghcr.io
             singularity push container.sif oras://ghcr.io/${GITHUB_REPOSITORY}/${IMAGE_NAME}:${TAG}
          fi
