name: Singularity Build (docker)
on: 
  push:

    # Edit the branches here if you want to change deploy behavior
    branches:
      - main
      - master

  # Do the builds on all pull requests (to test them)
  pull_request: []

jobs:
  changes:
    name: "Changed Singularity Recipes"
    runs-on: ubuntu-latest

    outputs:
      changed_files: ${{ steps.combine.outputs.changed_files }}

    steps:
      - id: files
        uses: Ana06/get-changed-files@v2.0.0
        with:
          format: 'json'

      - id: combine
        run: |
          echo '${{ steps.files.outputs.added_modified }}' > added_modified.json
          echo '${{ steps.files.outputs.renamed }}' > renamed.json
          changes="$(cat added_modified.json renamed.json | jq -r -s 'add | unique | sort')"
          echo "$changes"
          echo ::set-output name=changed_files::$(echo $changes | jq -c .)

  build-test-containers:
    needs:
      - changes
    runs-on: ubuntu-latest
    strategy:
      # Keep going on other deployments if anything bloops
      fail-fast: false
      matrix:
        changed_files: ${{ fromJSON(needs.changes.outputs.changed_files) }}
        singularity_version:
          - '3.8.3'

    container:
      image: quay.io/singularity/singularity:v${{ matrix.singularity_version }}
      options: --privileged

    name: Check ${{ matrix.changed_files }}
    steps:

      - name: Check out code for the container builds
        uses: actions/checkout@v2

      - name: Continue if Singularity Recipe
        run: |
          # Continue if we have a changed Singularity recipe
          if [[ "${{ matrix.changed_files }}" = *Singularity* ]]; then
             echo "keepgoing=true" >> $GITHUB_ENV
          fi          
      - name: Build Container
        if: ${{ env.keepgoing == 'true' }}
        env:
          recipe: ${{ matrix.changed_files }}
        run: |
          ls
          if [ -f "${{ matrix.changed_files }}" ]; then
             sudo -E singularity build container.sif ${{ matrix.changed_files }}
             # the name is anything after the "Singularity." in the definition filename
             name="$(echo "${recipe/Singularity\./}")"
             echo "Name is $name."
             echo "NAME=$name" >> $GITHUB_ENV
             # use latest as tag
             tag="latest"
             # Build the container and name by tag
             echo "Tag is $tag."
             echo "TAG=$tag" >> $GITHUB_ENV
          else
             echo "${{ matrix.changed_files }} is not found."
             echo "Present working directory: $PWD"
             ls
          fi
      - name: Login and Deploy Container
        if: (github.event_name != 'pull_request')
        env:
          keepgoing: ${{ env.keepgoing }}
        run: |         
          if [[ "${keepgoing}" == "true" ]]; then
             echo ${{ secrets.GITHUB_TOKEN }} | singularity remote login -u ${{ secrets.GHCR_USERNAME }} --password-stdin oras://ghcr.io
             singularity push container.sif oras://ghcr.io/${GITHUB_REPOSITORY}/${NAME}:${TAG}
          fi
